# Generated by Django 3.2.9 on 2021-11-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historical_characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='information_edited_at',
        ),
    ]
